const clothes = {
  prenda1: {
    name: "Flor Ombligo",
    code: "prenda1",
    price: "3",
    color: "",
    location: "../galeria/clothes/flor_ombligo.jpeg",
    category: "",
    nuevo: false,
    discount: 30,
  },
  prenda2: {
    name: "Flor Ombligo",
    code: "prenda2",
    price: "2",
    color: "",
    location: "../galeria/clothes/flor_vestido.jpeg",
    category: "",
    nuevo: true,
    discount: 0,
  },
  prenda3: {
    name: "Flor Ombligo",
    code: "prenda3",
    price: "2",
    color: "",
    location: "../galeria/clothes/jogger_rojo.jpeg",
    category: "",
    nuevo: false,
    discount: 20,
  },
  prenda4: {
    name: "Flor Ombligo",
    code: "prenda4",
    price: "2",
    color: "",
    location: "../galeria/clothes/ombligo_rayas.jpeg",
    category: "",
    nuevo: true,
    discount: 0,
  },
  prenda5: {
    name: "Flor Ombligo",
    code: "prenda5",
    price: "4",
    color: "",
    location: "../galeria/clothes/outfit_yellow_bicker.jpeg",
    category: "",
    nuevo: true,
    discount: 50,
  },
  prenda6: {
    name: "Flor Ombligo",
    code: "prenda6",
    price: "6",
    color: "",
    location: "../galeria/clothes/prenda_azul.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda7: {
    name: "Flor Ombligo",
    code: "prenda7",
    price: "6",
    color: "",
    location: "../galeria/clothes/prenda_roja.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda8: {
    name: "Flor Ombligo",
    code: "prenda8",
    price: "6",
    color: "",
    location: "../galeria/clothes/prenda_rosada_con_flores.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda9: {
    name: "Flor Ombligo",
    code: "prenda9",
    price: "$",
    color: "",
    location: "../galeria/clothes/punto_0manga_prenda.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda10: {
    name: "Flor Ombligo",
    code: "prenda10",
    price: "6",
    color: "",
    location: "../galeria/clothes/Rojo_un_brazo.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda11: {
    name: "Flor Ombligo",
    code: "prenda11",
    price: "8",
    color: "",
    location: "../galeria/clothes/rosado_fuerte_ombligo.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda12: {
    name: "Flor Ombligo",
    code: "prenda12",
    price: "8",
    color: "",
    location: "../galeria/clothes/rosado_princesa.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
};

export { clothes };
