const clothes = {
  prenda1: {
    name: "Flor T-Shirt",
    code: "prenda1",
    price: "8",
    color: "",
    location: "../galeria/clothes/Black_Grey.jpg",
    category: "",
    nuevo: false,
    discount: 30,
  },
  prenda2: {
    name: "Flor Skirt",
    code: "prenda2",
    price: "10",
    color: "",
    location: "../galeria/clothes/Brown Outfit.jpg",
    category: "",
    nuevo: true,
    discount: 0,
  },
  prenda3: {
    name: "Red Joggers",
    code: "prenda3",
    price: "12",
    color: "",
    location: "../galeria/clothes/Brown with Black.jpg",
    category: "",
    nuevo: false,
    discount: 20,
  },
  prenda4: {
    name: "Stripped Shirt",
    code: "prenda4",
    price: "8",
    color: "",
    location: "../galeria/clothes/casual_black.jpg",
    category: "",
    nuevo: true,
    discount: 0,
  },
  prenda5: {
    name: "Bob-Sponge T-Shirt",
    code: "prenda5",
    price: "9",
    color: "",
    location: "../galeria/clothes/Colorful_Sweater.jpg",
    category: "",
    nuevo: true,
    discount: 50,
  },
  prenda6: {
    name: "Blue Effect T-Shirt",
    code: "prenda6",
    price: "7",
    color: "",
    location: "../galeria/clothes/elegant_blue.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda7: {
    name: "Semi Hoddie",
    code: "prenda7",
    price: "8",
    color: "",
    location: "../galeria/clothes/gray_scarf.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda8: {
    name: "Flor Shirt (No Shoulders)",
    code: "prenda8",
    price: "7",
    color: "",
    location: "../galeria/clothes/green_coat.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda9: {
    name: "Dots Shirt",
    code: "prenda9",
    price: "7",
    color: "",
    location: "../galeria/clothes/Pink_White.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda10: {
    name: "One Long Sleeve Red Shirt",
    code: "prenda10",
    price: "8",
    color: "",
    location: "../galeria/clothes/scarf.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda11: {
    name: "Pink T-Shirt",
    code: "prenda11",
    price: "9",
    color: "",
    location: "../galeria/clothes/skirt_brown_square.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda12: {
    name: "Long Sleeve Pink Shirt",
    code: "prenda12",
    price: "11",
    color: "",
    location: "../galeria/clothes/Square_black_white.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda13: {
    name: "Long Sleeve Pink Shirt",
    code: "prenda12",
    price: "11",
    color: "",
    location: "../galeria/clothes/White_skirt.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda14: {
    name: "Long Sleeve Pink Shirt",
    code: "prenda12",
    price: "11",
    color: "",
    location: "../galeria/clothes/white_winter.jpg",
    category: "",
    nuevo: false,
    discount: 0,
  },
};

export { clothes };
