const clothes = {
  prenda1: {
    name: "Flor T-Shirt",
    code: "prenda1",
    price: "8",
    color: "",
    location: "../galeria/clothes/flor_ombligo.jpeg",
    category: "",
    nuevo: false,
    discount: 30,
  },
  prenda2: {
    name: "Flor Skirt",
    code: "prenda2",
    price: "10",
    color: "",
    location: "../galeria/clothes/flor_vestido.jpeg",
    category: "",
    nuevo: true,
    discount: 0,
  },
  prenda3: {
    name: "Red Joggers",
    code: "prenda3",
    price: "12",
    color: "",
    location: "../galeria/clothes/jogger_rojo.jpeg",
    category: "",
    nuevo: false,
    discount: 20,
  },
  prenda4: {
    name: "Stripped Shirt",
    code: "prenda4",
    price: "8",
    color: "",
    location: "../galeria/clothes/ombligo_rayas.jpeg",
    category: "",
    nuevo: true,
    discount: 0,
  },
  prenda5: {
    name: "Bob-Sponge T-Shirt",
    code: "prenda5",
    price: "9",
    color: "",
    location: "../galeria/clothes/outfit_yellow_bicker.jpeg",
    category: "",
    nuevo: true,
    discount: 50,
  },
  prenda6: {
    name: "Blue Effect T-Shirt",
    code: "prenda6",
    price: "7",
    color: "",
    location: "../galeria/clothes/prenda_azul.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda7: {
    name: "Semi Hoddie",
    code: "prenda7",
    price: "8",
    color: "",
    location: "../galeria/clothes/prenda_roja.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda8: {
    name: "Flor Shirt (No Shoulders)",
    code: "prenda8",
    price: "7",
    color: "",
    location: "../galeria/clothes/prenda_rosada_con_flores.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda9: {
    name: "Dots Shirt",
    code: "prenda9",
    price: "7",
    color: "",
    location: "../galeria/clothes/punto_0manga_prenda.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda10: {
    name: "One Long Sleeve Red Shirt",
    code: "prenda10",
    price: "8",
    color: "",
    location: "../galeria/clothes/Rojo_un_brazo.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda11: {
    name: "Pink T-Shirt",
    code: "prenda11",
    price: "9",
    color: "",
    location: "../galeria/clothes/rosado_fuerte_ombligo.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
  prenda12: {
    name: "Long Sleeve Pink Shirt",
    code: "prenda12",
    price: "11",
    color: "",
    location: "../galeria/clothes/rosado_princesa.jpeg",
    category: "",
    nuevo: false,
    discount: 0,
  },
};

export { clothes };
